package com.nimbus.weather.util

object CityNameResolver {

    private val TRANSLATION_SETS = listOf(
        mapOf("ru" to "Киев", "uk" to "Київ", "en" to "Kyiv", "cs" to "Kyjev"),
        mapOf("ru" to "Прага", "uk" to "Прага", "en" to "Prague", "cs" to "Praha"),
        mapOf("ru" to "Варшава", "uk" to "Варшава", "en" to "Warsaw", "cs" to "Varšava"),
        mapOf("ru" to "Берлин", "uk" to "Берлін", "en" to "Berlin", "cs" to "Berlín"),
        mapOf("ru" to "Париж", "uk" to "Париж", "en" to "Paris", "cs" to "Paříž"),
        mapOf("ru" to "Лондон", "uk" to "Лондон", "en" to "London", "cs" to "Londýn"),
        mapOf("ru" to "Минск", "uk" to "Мінськ", "en" to "Minsk", "cs" to "Minsk"),
        mapOf("ru" to "Москва", "uk" to "Москва", "en" to "Moscow", "cs" to "Moskva"),
        mapOf("ru" to "Санкт-Петербург", "uk" to "Санкт-Петербург", "en" to "Saint Petersburg", "cs" to "Petrohrad"),
        mapOf("ru" to "Вена", "uk" to "Відень", "en" to "Vienna", "cs" to "Vídeň"),
        mapOf("ru" to "Будапешт", "uk" to "Будапешт", "en" to "Budapest", "cs" to "Budapešť"),
        mapOf("ru" to "Братислава", "uk" to "Братислава", "en" to "Bratislava", "cs" to "Bratislava"),
        mapOf("ru" to "Белград", "uk" to "Белград", "en" to "Belgrade", "cs" to "Bělehrad"),
        mapOf("ru" to "София", "uk" to "Софія", "en" to "Sofia", "cs" to "Sofie"),
        mapOf("ru" to "Таллин", "uk" to "Таллінн", "en" to "Tallinn", "cs" to "Tallinn"),
        mapOf("ru" to "Рига", "uk" to "Рига", "en" to "Riga", "cs" to "Riga"),
        mapOf("ru" to "Вильнюс", "uk" to "Вільнюс", "en" to "Vilnius", "cs" to "Vilnius"),
        mapOf("ru" to "Хельсинки", "uk" to "Гельсінкі", "en" to "Helsinki", "cs" to "Helsinky"),
        mapOf("ru" to "Стокгольм", "uk" to "Стокгольм", "en" to "Stockholm", "cs" to "Stockholm"),
        mapOf("ru" to "Осло", "uk" to "Осло", "en" to "Oslo", "cs" to "Oslo"),
        mapOf("ru" to "Копенгаген", "uk" to "Копенгаген", "en" to "Copenhagen", "cs" to "Kodaň"),
        mapOf("ru" to "Амстердам", "uk" to "Амстердам", "en" to "Amsterdam", "cs" to "Amsterdam"),
        mapOf("ru" to "Брюссель", "uk" to "Брюссель", "en" to "Brussels", "cs" to "Brusel"),
        mapOf("ru" to "Мадрид", "uk" to "Мадрид", "en" to "Madrid", "cs" to "Madrid"),
        mapOf("ru" to "Рим", "uk" to "Рим", "en" to "Rome", "cs" to "Řím"),
        mapOf("ru" to "Афины", "uk" to "Афіни", "en" to "Athens", "cs" to "Athény"),
        mapOf("ru" to "Кишинёв", "uk" to "Кишинів", "en" to "Chișinău", "cs" to "Kišiněv"),
        mapOf("ru" to "Тбилиси", "uk" to "Тбілісі", "en" to "Tbilisi", "cs" to "Tbilisi"),
        mapOf("ru" to "Ереван", "uk" to "Єреван", "en" to "Yerevan", "cs" to "Jerevan"),
        mapOf("ru" to "Баку", "uk" to "Баку", "en" to "Baku", "cs" to "Baku"),
        mapOf("ru" to "Астана", "uk" to "Астана", "en" to "Astana", "cs" to "Astana"),
        mapOf("ru" to "Алматы", "uk" to "Алмати", "en" to "Almaty", "cs" to "Almaty"),
        mapOf("ru" to "Мюнхен", "uk" to "Мюнхен", "en" to "Munich", "cs" to "Mnichov"),
        mapOf("ru" to "Гамбург", "uk" to "Гамбург", "en" to "Hamburg", "cs" to "Hamburk"),
        mapOf("ru" to "Франкфурт", "uk" to "Франкфурт", "en" to "Frankfurt", "cs" to "Frankfurt"),
        mapOf("ru" to "Дрезден", "uk" to "Дрезден", "en" to "Dresden", "cs" to "Drážďany"),
        mapOf("ru" to "Лейпциг", "uk" to "Лейпциг", "en" to "Leipzig", "cs" to "Lipsko"),
        mapOf("ru" to "Харьков", "uk" to "Харків", "en" to "Kharkiv", "cs" to "Charkov"),
        mapOf("ru" to "Одесса", "uk" to "Одеса", "en" to "Odesa", "cs" to "Oděsa"),
        mapOf("ru" to "Днепр", "uk" to "Дніпро", "en" to "Dnipro", "cs" to "Dnipro"),
        mapOf("ru" to "Донецк", "uk" to "Донецьк", "en" to "Donetsk", "cs" to "Doněck"),
        mapOf("ru" to "Запорожье", "uk" to "Запоріжжя", "en" to "Zaporizhzhia", "cs" to "Zaporižžja"),
        mapOf("ru" to "Львов", "uk" to "Львів", "en" to "Lviv", "cs" to "Lvov"),
        mapOf("ru" to "Винница", "uk" to "Вінниця", "en" to "Vinnytsia", "cs" to "Vinnycja"),
        mapOf("ru" to "Черновцы", "uk" to "Чернівці", "en" to "Chernivtsi", "cs" to "Černovice"),
        mapOf("ru" to "Ивано-Франковск", "uk" to "Івано-Франківськ", "en" to "Ivano-Frankivsk", "cs" to "Ivano-Frankivsk"),
        mapOf("ru" to "Тернополь", "uk" to "Тернопіль", "en" to "Ternopil", "cs" to "Ternopil"),
        mapOf("ru" to "Луцк", "uk" to "Луцьк", "en" to "Lutsk", "cs" to "Luck"),
        mapOf("ru" to "Ровно", "uk" to "Рівне", "en" to "Rivne", "cs" to "Rovno"),
        mapOf("ru" to "Житомир", "uk" to "Житомир", "en" to "Zhytomyr", "cs" to "Žytomyr"),
        mapOf("ru" to "Херсон", "uk" to "Херсон", "en" to "Kherson", "cs" to "Cherson"),
        mapOf("ru" to "Николаев", "uk" to "Миколаїв", "en" to "Mykolaiv", "cs" to "Mykolajiv"),
        mapOf("ru" to "Полтава", "uk" to "Полтава", "en" to "Poltava", "cs" to "Poltava"),
        mapOf("ru" to "Сумы", "uk" to "Суми", "en" to "Sumy", "cs" to "Sumy"),
        mapOf("ru" to "Черкассы", "uk" to "Черкаси", "en" to "Cherkasy", "cs" to "Čerkasy"),
        mapOf("ru" to "Чернигов", "uk" to "Чернігів", "en" to "Chernihiv", "cs" to "Černihiv"),
        mapOf("ru" to "Ужгород", "uk" to "Ужгород", "en" to "Uzhhorod", "cs" to "Užhorod"),
        mapOf("ru" to "Хмельницкий", "uk" to "Хмельницький", "en" to "Khmelnytskyi", "cs" to "Chmelnyckyj"),
        mapOf("ru" to "Кропивницкий", "uk" to "Кропивницький", "en" to "Kropyvnytskyi", "cs" to "Kropyvnyckyj"),
        mapOf("ru" to "Кривой Рог", "uk" to "Кривий Ріг", "en" to "Kryvyi Rih", "cs" to "Kryvyj Rih"),
        mapOf("ru" to "Мариуполь", "uk" to "Маріуполь", "en" to "Mariupol", "cs" to "Mariupol"),
        mapOf("ru" to "Казань", "uk" to "Казань", "en" to "Kazan", "cs" to "Kazaň"),
        mapOf("ru" to "Нижний Новгород", "uk" to "Нижній Новгород", "en" to "Nizhny Novgorod", "cs" to "Nižnij Novgorod"),
        mapOf("ru" to "Новосибирск", "uk" to "Новосибірськ", "en" to "Novosibirsk", "cs" to "Novosibirsk"),
        mapOf("ru" to "Екатеринбург", "uk" to "Єкатеринбург", "en" to "Yekaterinburg", "cs" to "Jekatěrinburg"),
        mapOf("ru" to "Самара", "uk" to "Самара", "en" to "Samara", "cs" to "Samara"),
        mapOf("ru" to "Омск", "uk" to "Омськ", "en" to "Omsk", "cs" to "Omsk"),
        mapOf("ru" to "Челябинск", "uk" to "Челябінськ", "en" to "Chelyabinsk", "cs" to "Čeljabinsk"),
        mapOf("ru" to "Ростов-на-Дону", "uk" to "Ростов-на-Дону", "en" to "Rostov-on-Don", "cs" to "Rostov na Donu"),
        mapOf("ru" to "Уфа", "uk" to "Уфа", "en" to "Ufa", "cs" to "Ufa"),
        mapOf("ru" to "Красноярск", "uk" to "Красноярськ", "en" to "Krasnoyarsk", "cs" to "Krasnojarsk"),
        mapOf("ru" to "Воронеж", "uk" to "Воронеж", "en" to "Voronezh", "cs" to "Voroněž"),
        mapOf("ru" to "Пермь", "uk" to "Перм", "en" to "Perm", "cs" to "Perm"),
        mapOf("ru" to "Волгоград", "uk" to "Волгоград", "en" to "Volgograd", "cs" to "Volgograd"),
        mapOf("ru" to "Калининград", "uk" to "Калінінград", "en" to "Kaliningrad", "cs" to "Kaliningrad"),
        mapOf("ru" to "Саратов", "uk" to "Саратов", "en" to "Saratov", "cs" to "Saratov"),
        mapOf("ru" to "Тюмень", "uk" to "Тюмень", "en" to "Tyumen", "cs" to "Ťumeň"),
        mapOf("ru" to "Ижевск", "uk" to "Іжевськ", "en" to "Izhevsk", "cs" to "Iževsk"),
        mapOf("ru" to "Барнаул", "uk" to "Барнаул", "en" to "Barnaul", "cs" to "Barnaul"),
        mapOf("ru" to "Ульяновск", "uk" to "Ульяновськ", "en" to "Ulyanovsk", "cs" to "Uljanovsk"),
        mapOf("ru" to "Иркутск", "uk" to "Іркутськ", "en" to "Irkutsk", "cs" to "Irkutsk"),
        mapOf("ru" to "Хабаровск", "uk" to "Хабаровськ", "en" to "Khabarovsk", "cs" to "Chabarovsk"),
        mapOf("ru" to "Владивосток", "uk" to "Владивосток", "en" to "Vladivostok", "cs" to "Vladivostok"),
        mapOf("ru" to "Ярославль", "uk" to "Ярославль", "en" to "Yaroslavl", "cs" to "Jaroslavl"),
        mapOf("ru" to "Махачкала", "uk" to "Махачкала", "en" to "Makhachkala", "cs" to "Machačkala"),
        mapOf("ru" to "Томск", "uk" to "Томськ", "en" to "Tomsk", "cs" to "Tomsk"),
        mapOf("ru" to "Оренбург", "uk" to "Оренбург", "en" to "Orenburg", "cs" to "Orenburg"),
        mapOf("ru" to "Кемерово", "uk" to "Кемерове", "en" to "Kemerovo", "cs" to "Kemerovo"),
        mapOf("ru" to "Рязань", "uk" to "Рязань", "en" to "Ryazan", "cs" to "Rjazaň"),
        mapOf("ru" to "Астрахань", "uk" to "Астрахань", "en" to "Astrakhan", "cs" to "Astrachaň"),
        mapOf("ru" to "Пенза", "uk" to "Пенза", "en" to "Penza", "cs" to "Penza"),
        mapOf("ru" to "Липецк", "uk" to "Липецьк", "en" to "Lipetsk", "cs" to "Lipeck"),
        mapOf("ru" to "Киров", "uk" to "Кіров", "en" to "Kirov", "cs" to "Kirov"),
        mapOf("ru" to "Чебоксары", "uk" to "Чебоксари", "en" to "Cheboksary", "cs" to "Čeboksary"),
        mapOf("ru" to "Тула", "uk" to "Тула", "en" to "Tula", "cs" to "Tula"),
        mapOf("ru" to "Курск", "uk" to "Курськ", "en" to "Kursk", "cs" to "Kursk"),
        mapOf("ru" to "Севастополь", "uk" to "Севастополь", "en" to "Sevastopol", "cs" to "Sevastopol"),
        mapOf("ru" to "Симферополь", "uk" to "Сімферополь", "en" to "Simferopol", "cs" to "Simferopol"),
        mapOf("ru" to "Брно", "uk" to "Брно", "en" to "Brno", "cs" to "Brno"),
        mapOf("ru" to "Острава", "uk" to "Острава", "en" to "Ostrava", "cs" to "Ostrava"),
        mapOf("ru" to "Пльзень", "uk" to "Пльзень", "en" to "Plzeň", "cs" to "Plzeň"),
        mapOf("ru" to "Либерец", "uk" to "Ліберець", "en" to "Liberec", "cs" to "Liberec"),
        mapOf("ru" to "Оломоуц", "uk" to "Оломоуць", "en" to "Olomouc", "cs" to "Olomouc"),
        mapOf("ru" to "Ческе-Будеёвице", "uk" to "Чеські Будейовиці", "en" to "České Budějovice", "cs" to "České Budějovice"),
        mapOf("ru" to "Градец-Кралове", "uk" to "Градець-Кралове", "en" to "Hradec Králové", "cs" to "Hradec Králové"),
        mapOf("ru" to "Усти-над-Лабем", "uk" to "Усті-над-Лабем", "en" to "Ústí nad Labem", "cs" to "Ústí nad Labem"),
        mapOf("ru" to "Пардубице", "uk" to "Пардубіце", "en" to "Pardubice", "cs" to "Pardubice"),
        mapOf("ru" to "Злин", "uk" to "Злін", "en" to "Zlín", "cs" to "Zlín"),
        mapOf("ru" to "Гданьск", "uk" to "Гданськ", "en" to "Gdańsk", "cs" to "Gdaňsk"),
        mapOf("ru" to "Краков", "uk" to "Краків", "en" to "Kraków", "cs" to "Krakov"),
        mapOf("ru" to "Вроцлав", "uk" to "Вроцлав", "en" to "Wrocław", "cs" to "Vratislav"),
        mapOf("ru" to "Познань", "uk" to "Познань", "en" to "Poznań", "cs" to "Poznaň")
    )

    private val KNOWN_TRANSLATIONS: Map<String, Map<String, String>> = run {
        val result = HashMap<String, Map<String, String>>(TRANSLATION_SETS.size * 4)
        for (set in TRANSLATION_SETS) {
            for ((_, name) in set) {
                result[name] = set
            }
        }
        result
    }

    fun displayName(
        name: String,
        localNames: Map<String, String> = emptyMap(),
        languageCode: String
    ): String {
        localNames[languageCode]?.takeIf { it.isNotBlank() }?.let { return it }
        KNOWN_TRANSLATIONS[name]?.get(languageCode)?.let { return it }
        return name
    }
}
